FROM node:22-alpine

WORKDIR /app

COPY ../app/package*.json ./

RUN npm ci --omit=dev

COPY ../app .

RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup

RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE 3000

CMD ["node","index.js"]