######## Builder ########

FROM node:22-alpine AS builder

WORKDIR /app

COPY app/package*.json ./

RUN npm ci --omit=dev

COPY app .

######## Production ########

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000

CMD ["node","index.js"]